lib/sanctions_web/router.ex
defmodule SanctionsWeb.Router do
  use SanctionsWeb, :router
  use Kaffy.Routes #, scope: "/admin", pipe_through: [:some_plug, :authenticate]

  import SanctionsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SanctionsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SanctionsWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SanctionsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SanctionsWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", SanctionsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SanctionsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SanctionsWeb do
    pipe_through [:browser]

    live "/personseu", PersonEUListLive
    resources "/personseu", PersonEUController

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm

    live "/persons", PersonListLive
    live "/persons/new", PersonLive.Index, :new
    live "/persons/:id/edit", PersonLive.Index, :edit

    live "/persons/:id", PersonLive.Show, :show
    live "/persons/:id/show/edit", PersonLive.Show, :edit
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/sanctions_web/controllers/user_reset_password_controller.ex
defmodule SanctionsWeb.UserResetPasswordController do
  use SanctionsWeb, :controller

  alias Sanctions.Accounts

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_user_password(conn.assigns.user))
  end

  # Do not log in the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Accounts.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/sanctions_web/views/user_reset_password_view.ex
defmodule SanctionsWeb.UserResetPasswordView do
  use SanctionsWeb, :view
end

lib/sanctions_web/templates/user_reset_password/edit.html.eex
<h5 class="pb-2 px-5 text-lg leading-normal text-center">Reset Password</h5>
<%= form_for @changeset, Routes.user_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <small>Oops, something went wrong! Please check the errors below.</small>
    </div>
  <% end %>

  <div class="mt-4 mb-4">
    <%= label f, :password, "New password", class: "tag-label" %>
    <%= password_input f, :password, required: true, class: "tag-input" %>
    <%= error_tag f, :password %>
  </div>

  <div class="mb-4">
    <%= label f, :password_confirmation, "Confirm new password", class: "tag-label" %>
    <%= password_input f, :password_confirmation, required: true, class: "tag-input" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="mt-3">
    <%= submit "Reset password", class: "btn btn-dark w-full" %>
  </div>
<% end %>

<div class="mt-3 text-center text-gray-600">
  <small>I do rememebr my password</small>
</div>

<div class="mt-3">
  <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "btn btn-link btn-sm" %>
  <%= link "Login", to: Routes.user_session_path(@conn, :new), class: "btn btn-link btn-sm" %>
</div>

lib/sanctions_web/templates/user_reset_password/new.html.eex
<h5 class="pb-2 px-5 text-lg leading-normal text-center">Forgot your password?</h5>
<%= form_for :user, Routes.user_reset_password_path(@conn, :create), fn f -> %>
  <div class="mt-4 mb-4">
    <%= label f, :email, class: "tag-label" %>
    <%= text_input f, :email, required: true, class: "tag-input" %>
  </div>

  <div class="mt-3">
    <%= submit "Send password reset instructions", class: "btn btn-dark w-full" %>
  </div>
<% end %>

<div class="mt-3 text-center text-gray-600">
  <small>I do rememebr my password</small>
</div>

<div class="mt-3">
  <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "btn btn-link btn-sm" %>
  <%= link "Login", to: Routes.user_session_path(@conn, :new), class: "btn btn-link btn-sm" %>
</div>