lib/sanctions_web/router.ex
defmodule SanctionsWeb.Router do
  use SanctionsWeb, :router
  use Kaffy.Routes #, scope: "/admin", pipe_through: [:some_plug, :authenticate]

  import SanctionsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SanctionsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SanctionsWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SanctionsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SanctionsWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", SanctionsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SanctionsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SanctionsWeb do
    pipe_through [:browser]

    live "/personseu", PersonEUListLive
    resources "/personseu", PersonEUController

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm

    live "/persons", PersonListLive
    live "/persons/new", PersonLive.Index, :new
    live "/persons/:id/edit", PersonLive.Index, :edit

    live "/persons/:id", PersonLive.Show, :show
    live "/persons/:id/show/edit", PersonLive.Show, :edit
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/sanctions_web/views/layout_view.ex
defmodule SanctionsWeb.LayoutView do
  use SanctionsWeb, :view
end

lib/sanctions_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
  <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "btn btn-sm btn-link" %>
  <%= link "Logout", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "btn btn-sm btn-link" %>
<% else %>
  <%= link "Sign In", to: Routes.user_session_path(@conn, :new), class: "btn btn-sm btn-link" %>
  <%= link "Get Started", to: Routes.user_registration_path(@conn, :new), class: "btn btn-sm btn-primary" %>
<% end %>

lib/sanctions_web/templates/layout/app.html.eex
<main role="main" class="container mx-auto mb-8 px-4 max-w-6xl">
  <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/sanctions_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><%= assigns[:title] %></title>
    <style>
      /* -------------------------------------
          GLOBAL
          A very basic CSS reset
      ------------------------------------- */
      * {
        margin: 0;
        padding: 0;
        font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
        box-sizing: border-box;
        font-size: 14px;
      }

      img {
        max-width: 100%;
      }

      body {
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: none;
        width: 100% !important;
        height: 100%;
        line-height: 1.6;
      }

      /* Let's make sure all tables have defaults */
      table td {
        vertical-align: top;
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */
      body {
        background-color: #f6f6f6;
      }

      .body-wrap {
        background-color: #f6f6f6;
        width: 100%;
      }

      .container {
        display: block !important;
        max-width: 600px !important;
        margin: 0 auto !important;
        /* makes it centered */
        clear: both !important;
      }

      .content {
        max-width: 600px;
        margin: 0 auto;
        display: block;
        padding: 20px;
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #fff;
        border: 1px solid #e9e9e9;
        border-radius: 3px;
      }

      .content-wrap {
        padding: 20px;
      }

      .content-block {
        padding: 0 0 20px;
      }

      .header {
        width: 100%;
        margin-bottom: 20px;
      }

      .footer {
        width: 100%;
        clear: both;
        color: #999;
        padding: 20px;
      }
      .footer a {
        color: #999;
      }
      .footer p, .footer a, .footer unsubscribe, .footer td {
        font-size: 12px;
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1, h2, h3 {
        font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        color: #000;
        margin: 40px 0 0;
        line-height: 1.2;
        font-weight: 400;
      }

      h1 {
        font-size: 32px;
        font-weight: 500;
      }

      h2 {
        font-size: 24px;
      }

      h3 {
        font-size: 18px;
      }

      h4 {
        font-size: 14px;
        font-weight: 600;
      }

      p, ul, ol {
        margin-bottom: 10px;
        font-weight: normal;
      }
      p li, ul li, ol li {
        margin-left: 5px;
        list-style-position: inside;
      }

      /* -------------------------------------
          LINKS & BUTTONS
      ------------------------------------- */
      a {
        color: #348eda;
        text-decoration: underline;
      }

      .btn-primary {
        text-decoration: none;
        color: #FFF;
        background-color: #348eda;
        border: solid #348eda;
        border-width: 10px 20px;
        line-height: 2;
        font-weight: bold;
        text-align: center;
        cursor: pointer;
        display: inline-block;
        border-radius: 5px;
        text-transform: capitalize;
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0;
      }

      .first {
        margin-top: 0;
      }

      .aligncenter {
        text-align: center;
      }

      .alignright {
        text-align: right;
      }

      .alignleft {
        text-align: left;
      }

      .clear {
        clear: both;
      }

      /* -------------------------------------
          ALERTS
          Change the class depending on warning email, good email or bad email
      ------------------------------------- */
      .alert {
        font-size: 16px;
        color: #fff;
        font-weight: 500;
        padding: 20px;
        text-align: center;
        border-radius: 3px 3px 0 0;
      }
      .alert a {
        color: #fff;
        text-decoration: none;
        font-weight: 500;
        font-size: 16px;
      }
      .alert.alert-warning {
        background: #ff9f00;
      }
      .alert.alert-bad {
        background: #d0021b;
      }
      .alert.alert-good {
        background: #68b90f;
      }

      /* -------------------------------------
          INVOICE
          Styles for the billing table
      ------------------------------------- */
      .invoice {
        margin: 40px auto;
        text-align: left;
        width: 80%;
      }
      .invoice td {
        padding: 5px 0;
      }
      .invoice .invoice-items {
        width: 100%;
      }
      .invoice .invoice-items td {
        border-top: #eee 1px solid;
      }
      .invoice .invoice-items .total td {
        border-top: 2px solid #333;
        border-bottom: 2px solid #333;
        font-weight: 700;
      }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 640px) {
        h1, h2, h3, h4 {
          font-weight: 600 !important;
          margin: 20px 0 5px !important;
        }

        h1 {
          font-size: 22px !important;
        }

        h2 {
          font-size: 18px !important;
        }

        h3 {
          font-size: 16px !important;
        }

        .container {
          width: 100% !important;
        }

        .content, .content-wrapper {
          padding: 10px !important;
        }

        .invoice {
          width: 100% !important;
        }
      }
    </style>
  </head>
  <body>
    <!-- start preheader -->
    <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
      <%= assigns[:preheader] %>

    </div>
    <!-- end preheader -->
    <table class="body-wrap">
      <tr>
        <td></td>
        <td class="container" width="600">
          <div class="content">
            <table class="main" width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td class="content-wrap">
                  <%= @inner_content %>
                </td>
              </tr>
            </table>
            <div class="footer">
              <table width="100%">
                <tr>
                  <td class="aligncenter content-block">
                    Sanctions - 2020
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </td>
        <td></td>
      </tr>
    </table>
  </body>
</html>

lib/sanctions_web/templates/layout/email.text.eex
<%= @inner_content %>

lib/sanctions_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Sanctions", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="flex flex-col h-full bg-gray-700">
    <header>
      <nav class="flex flex-wrap items-center justify-between py-2 px-4 fixed top-0 right-0 left-0 z-30 bg-gray-700">
        <a class="inline-block mr-4 py-1 text-xl text-gray-300" href="#"><i class="fas fa-bolt"></i> Sanctions</a>
      </nav>
    </header>

    <main role="main" class="container mx-auto mb-8 px-4 max-w-6xl">
      <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="flex justify-center p-2">
        <div class="card w-full max-w-xs">
          <div class="card-body">
            <%= @inner_content %>
          </div>
        </div>
      </div>
    </main>

    <footer class="footer bg-gray-800 text-gray-600 mt-auto py-6">
      <div class="container mx-auto px-4 max-w-6xl">
        <span class="text-muted">Sanctions</span>
      </div>
    </footer>
  </body>
</html>